title: Portfolio
collections:
  - articles
navlinks:
  - name: Home
    url: index.html
  - name: Shop
    url: shop.html
  - name: Local
    url: local.html
  - name: Contact Us
    url: contact.html
footerlinks:
  - name: Site
    url: https://mchy8.github.io/Portfolio/index.html
  - name: Github
    url: https://github.com/mchy8/
  - name: Source
    url: https://github.com/mchy8/mchy8.github.io/tree/master/Portfolio
